In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
df=pd.read_csv("car.csv")
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000.0,100000.0,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000.0,46000.0,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000.0,141000.0,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999.0,80000.0,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000.0,83000.0,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000.0,90000.0,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000.0,40000.0,Petrol,Individual,Manual,First Owner

In [41]:
df.describe()

              year  selling_price      km_driven
count  4340.000000   4.339000e+03    4338.000000
mean   2013.090783   5.042205e+05   66243.652374
std       4.215344   5.785829e+05   46636.666295
min    1992.000000   2.000000e+04       1.000000
25%    2011.000000   2.100000e+05   35000.000000
50%    2014.000000   3.500000e+05   60000.000000
75%    2016.000000   6.000000e+05   90000.000000
max    2020.000000   8.900000e+06  806599.000000

In [42]:
df1=df.drop(columns=['name'],axis=1)

In [43]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           4340 non-null   int64
 1   selling_price  4339 non-null   float64
 2   km_driven      4338 non-null   float64
 3   fuel           4340 non-null   object
 4   seller_type    4340 non-null   object
 5   transmission   4340 non-null   object
 6   owner          4340 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 237.5+ KB

In [44]:
df1.isna().sum()

year             0
selling_price    1
km_driven        2
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [45]:
df1['km_driven']=df1['km_driven'].fillna(df1['km_driven'].mean())

In [46]:
df1.isna().sum()

year             0
selling_price    1
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [47]:
df1=df1.dropna()

In [48]:

df['owner'].unique()

array(['First Owner', 'Second Owner', 'Fourth & Above Owner',
       'Third Owner', 'Test Drive Car'], dtype=object)

In [49]:
df['fuel'].value_counts()

fuel
Diesel      2153
Petrol      2123
CNG           40
LPG           23
Electric       1
Name: count, dtype: int64

In [50]:
df['seller_type'].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [51]:
df['transmission'].value_counts()

transmission
Manual       3892
Automatic     448
Name: count, dtype: int64

array([1., 0.])

In [52]:
df1['owner']=df1['owner'].replace({'First Owner':5, 'Second Owner':4, 'Fourth & Above Owner':3,
       'Third Owner':2, 'Test Drive Car':1})
df1['transmission']=df1['transmission'].replace({'Manual':1,'Automatic':2})
df1['fuel']=df1['fuel'].replace({'Diesel':5,'Petrol':4,'CNG':3,'LPG':2,'Electric':1})
df1['seller_type']=df1['seller_type'].replace({'Individual':3, 'Dealer':2, 'Trustmark Dealer':1})

/tmp/ipykernel_5363/2739508185.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['owner']=df1['owner'].replace({'First Owner':5, 'Second Owner':4, 'Fourth & Above Owner':3,
/tmp/ipykernel_5363/2739508185.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['transmission']=df1['transmission'].replace({'Manual':1,'Automatic':2})
/tmp/ipykernel_5363/2739508185.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['fuel']=df1['fuel'].replace({'Diesel':5,'Petrol':4,'CNG':3,'LPG':2,'Electric':1})
/tmp/ipykernel_5363/2739508185.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['seller_type']=df1['seller_type'].replace({'Individual':3, 'Dealer':2, 'Trustmark Dealer':1})

In [53]:
df1

      year  selling_price  km_driven  fuel  seller_type  transmission  owner
0     2007        60000.0    70000.0     4            3             1      5
1     2007       135000.0    50000.0     4            3             1      5
2     2012       600000.0   100000.0     5            3             1      5
3     2017       250000.0    46000.0     4            3             1      5
4     2014       450000.0   141000.0     5            3             1      4
...    ...            ...        ...   ...          ...           ...    ...
4335  2014       409999.0    80000.0     5            3             1      4
4336  2014       409999.0    80000.0     5            3             1      4
4337  2009       110000.0    83000.0     4            3             1      4
4338  2016       865000.0    90000.0     5            3             1      5
4339  2016       225000.0    40000.0     4            3             1      5

[4339 rows x 7 columns]

In [55]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

df1[['year','km_driven','fuel','seller_type','transmission','owner']] = scaler.fit_transform(
    df1[['year','km_driven','fuel','seller_type','transmission','owner']]
)

In [56]:
df1

,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,0.535714,60000.0,0.086783,0.75,1.0,0.0,1.00
1,0.535714,135000.0,0.061988,0.75,1.0,0.0,1.00
2,0.714286,600000.0,0.123976,1.00,1.0,0.0,1.00
3,0.892857,250000.0,0.057028,0.75,1.0,0.0,1.00
4,0.785714,450000.0,0.174807,1.00,1.0,0.0,0.75
...,...,...,...,...,...,...,...
4335,0.785714,409999.0,0.099181,1.00,1.0,0.0,0.75
4336,0.785714,409999.0,0.099181,1.00,1.0,0.0,0.75
4337,0.607143,110000.0,0.102900,0.75,1.0,0.0,0.75
4338,0.857143,865000.0,0.111579,1.00,1.0,0.0,1.00
4339,0.857143,225000.0,0.049590,0.75,1.0,0.0,1.00

In [57]:
df1.corr()

,year,selling_price,km_driven,fuel,seller_type,transmission,owner
year,1.000000,0.413812,-0.419610,0.124278,-0.182323,0.143724,0.392103
selling_price,0.413812,1.000000,-0.192351,0.275362,-0.240599,0.530187,0.189648
km_driven,-0.419610,-0.192351,1.000000,0.249805,0.186304,-0.119550,-0.276128
fuel,0.124278,0.275362,0.249805,1.000000,-0.034690,0.052190,0.008169
seller_type,-0.182323,-0.240599,0.186304,-0.034690,1.000000,-0.200157,-0.208910
transmission,0.143724,0.530187,-0.119550,0.052190,-0.200157,1.000000,0.074883
owner,0.392103,0.189648,-0.276128,0.008169,-0.208910,0.074883,1.000000

In [58]:
x1=df1[['transmission']]
y1=df1['selling_price']

In [59]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
X_train,X_test,y_train,y_test=train_test_split(x1,y1, random_state=42, test_size=0.3)

print("X train=",X_train.shape)
print("Y train=",y_train.shape)
print("X test=",X_test.shape)
print("Y test=",y_test.shape)

X train= (3037, 1)
Y train= (3037,)
X test= (1302, 1)
Y test= (1302,)

In [60]:
from sklearn.linear_model import LinearRegression

model1=LinearRegression().fit(X_train,y_train)

In [61]:
y_pred=model1.predict(X_test)
y_pred

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"R-squared: {r2}")

Mean Squared Error: 202988326604.96265
Mean Absolute Error: 288623.14899204567
R-squared: 0.27056025371149817

In [62]:
df['selling_price'].max()

8900000.0

In [63]:
df['selling_price'].min()

20000.0

In [64]:
user_trans = input("Enter the year of the car for prediction: ")
if user_trans.lower() == 'manual':
    user_trans1 = 1
elif user_trans.lower() == 'automatic':
    user_trans1 =2
user_input_df = pd.DataFrame({'transmission': [user_trans1]})


predicted_price = model1.predict(user_input_df)

# Access the first element of the array for formatting
print(f"For a car having transmission {user_trans}, the predicted selling price is: {predicted_price[0]:,.2f}")

Enter the year of the car for prediction: manual
For a car having transmission manual, the predicted selling price is: 1,450,537.20

In [65]:
x2=df1.drop(columns=['selling_price'],axis=1)
y2=df1['selling_price']

X2_train,X2_test,y2_train,y2_test=train_test_split(x2,y2, random_state=42, test_size=0.3)

print("X train=",X2_train.shape)
print("Y train=",y2_train.shape)
print("X test=",X2_test.shape)
print("Y test=",y2_test.shape)

X train= (3037, 6)
Y train= (3037,)
X test= (1302, 6)
Y test= (1302,)

In [66]:
X2_train

          year  km_driven  fuel  seller_type  transmission  owner
930   0.750000   0.072526  1.00          0.5           1.0   1.00
2799  0.892857   0.018595  0.75          1.0           0.0   1.00
2118  0.678571   0.011811  0.75          0.5           0.0   1.00
2880  0.857143   0.030993  1.00          1.0           0.0   1.00
246   0.928571   0.030993  1.00          1.0           0.0   1.00
...        ...        ...   ...          ...           ...    ...
3445  0.392857   0.123976  0.75          1.0           0.0   0.75
466   0.678571   0.099181  1.00          1.0           0.0   1.00
3093  0.750000   0.028142  1.00          0.5           0.0   0.75
3773  0.714286   0.083064  0.50          0.5           0.0   0.75
860   0.750000   0.099181  0.75          1.0           0.0   1.00

[3037 rows x 6 columns]

In [67]:
model2=LinearRegression().fit(X2_train,y2_train)

In [68]:
y_pred2=model2.predict(X2_test)
y_pred2

mse = mean_squared_error(y2_test, y_pred2)
mae = mean_absolute_error(y2_test, y_pred2)
r2 = r2_score(y2_test, y_pred2)

print(f"Mean Squared Error: {mse}")
print(f"Mean Absolute Error: {mae}")
print(f"R-squared: {r2}")

Mean Squared Error: 146701630578.96063
Mean Absolute Error: 224508.1978878259
R-squared: 0.47282682714124913

In [69]:
owner_map = {
    'first owner': 5,
    'second owner': 4,
    'fourth & above owner': 3,
    'third owner': 2,
    'test drive car': 1
}

fuel_map = {
    'diesel': 5,
    'petrol': 4,
    'cng': 3,
    'lpg': 2,
    'electric': 1
}

seller_map = {
    'individual': 3,
    'dealer': 2,
    'trustmark dealer': 1
}

trans_map = {
    'manual': 1,
    'automatic': 2
}


owner_encoded = owner_map.get(input("Enter Owner Type: ").lower())
fuel_encoded = fuel_map.get(input("Enter Fuel Type: ").lower())
seller_encoded = seller_map.get(input("Enter Seller Type: ").lower())
trans_encoded = trans_map.get(input("Enter Transmission Type: ").lower())
km_driven = float(input("Enter KM Driven: "))
year=int(input("Enter Year: "))

user_input = pd.DataFrame({
    'year': [year],
    'km_driven': [km_driven],
    'fuel': [fuel_encoded],
    'seller_type': [seller_encoded],
    'transmission': [trans_encoded],
    'owner': [owner_encoded]
})

user_input = scaler.transform(user_input)

user_input_df = pd.DataFrame(user_input, columns=x2.columns)

predicted_price = model2.predict(user_input_df)

print(f"For the given car details, the predicted selling price is: {predicted_price[0]:,.2f}")

KeyboardInterrupt: Interrupted by user